Quiz-2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home

  get '/requests/new' => 'requests#new', as: :new_request

  post '/requests' => 'requests#create', as: :requests

  get "/requests/:id" => 'requests#show', as: :request

  get "/requests" => 'requests#index'

  get '/requests/:id/edit' => 'requests#edit', as: :edit_request

  patch '/requests/:id' => 'requests#update'

  delete 'requests/:id' => 'requests#destroy'

  patch '/requests/:id/actions' => 'requests#actions', as: :actions_status


end

Quiz-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Quiz-2/app/models/request.rb
class Request < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  after_initialize :set_defaults

  def self.search(search)
    where("name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE ? ", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  private

  def set_defaults
    self.actions ||= "Not Done"
  end

end

Quiz-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Quiz-2/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

Quiz-2/app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).permit([:name, :email, :department, :message, :actions])
    @request = Request.new request_params
    if @request.save
      redirect_to request_path(@request)
    else
      render :new_request
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def index
    @requests = Request.all
    if params[:search]
      @requests = Request.search(params[:search]).paginate(:page => params[:page], :per_page => 7).order(actions: :desc)
    else
      @requests = Request.paginate(:page => params[:page], :per_page => 7).order(actions: :desc)
    end
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    @request = Request.find params[:id]
    request_params = params.require(:request).permit(:name, :email, :department, :message, :actions)
    if @request.update request_params
      redirect_to request_path(@request)
    else
      render :edit
    end
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

  def actions
    request = Request.find params[:id]
    if request.actions == "Not Done"
      request.update_attribute(:actions, "Done")
    else
      request.update_attribute(:actions, "Not Done")
    end
    redirect_to requests_path
  end

end

Quiz-2/app/helpers/application_helper.rb
module ApplicationHelper
end

Quiz-2/app/helpers/home_helper.rb
module HomeHelper
end

Quiz-2/app/helpers/requests_helper.rb
module RequestsHelper
end

Quiz-2/app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to my Quiz-2 App</h1>
  <br>
  <h3>If you need to create a request please click <a href='/requests/new'>Here</a></h3>
</div>

Quiz-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav>
      <div id="nav-bar">
      <%= link_to 'Home', home_path %>
      |
      <%= link_to 'New Request', new_request_path %>
      |
      <%= link_to 'All Requests', requests_path %>
      
    </div>
  </nav>
  <br>
  <br>
  <hr>
    <%= yield %>
  </body>
</html>

Quiz-2/app/views/requests/edit.html.erb
<div class="container">
<h1>Edit Request</h1>

<%= @request.errors.full_messages.join(", ")%>

  <%= form_for @request do |f| %>

    <div>
      <%=f.label :name %>
      <%=f.text_field :name %>
    </div>
    <br>
    <div>
      <%=f.label :email %>
      <%=f.text_field :email %>
    </div>
    <br>
    <div>
      <%=f.label :department %>
      <%= f.radio_button :department, 'Sales' %> Sales
      <%= f.radio_button :department, 'Marketing' %> Marketing
      <%= f.radio_button :department, 'Technical' %> Technical
    </div>
    <br>
    <div>
      <%=f.label :message %>
      <%=f.text_area :message %>
    </div>
    <br>
    <br>

    <%= f.submit "Save" %>

  <% end %>
</div>

Quiz-2/app/views/requests/index.html.erb
<div class="container">

  <h1>Support Requests</h1>
  <br>

  <div>
    <%= form_tag(requests_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
    <% end %>
  </div>

  <div>
    <% if @requests.present? %>
      <% @requests %>
    <% else %>
      <p>There are no Request containing the term(s) <%= params[:search] %>.</p>
    <% end %>
  </div>
  <br>

  <table class="table table-bordered">
    <tr>
      <td>#</td>
      <td>Name</td>
      <td>Email</td>
      <td>Department</td>
      <td>Message</td>
      <td>Actions</td>
    </tr>
    <% @requests.each do |r|%>
    <tr>
      <td><%= link_to r.id, request_path(r) %></td>
      <td><%= link_to r.name, request_path(r) %></td>
      <td><%= link_to r.email, request_path(r) %></td>
      <td><%= link_to r.department, request_path(r) %></td>
      <td><%= link_to r.message, request_path(r) %></td>
      <td>
        <% if r.actions == "Not Done" %>
        <%= link_to "Not Done", actions_status_path(r), :method => :patch%>
        <%else%>
        <%= link_to "Done", actions_status_path(r), :method => :patch%>
        <%end%>
         <hr>
        <%= link_to "Edit", edit_request_path(r)%><br>
        <%= link_to "Delete", request_path(r),
                            method: :delete,
                            data: {confirm: 'Are you sure you want to delete this request?'}%>
      </td>
    </tr>
    <%end%>
  </table>
  <div class="container" id="pag">
    <%= will_paginate @requests %>
  </div>
</div>

Quiz-2/app/views/requests/new.html.erb
<div class="container">
  <h1>Make a New Request here:</h1>
  <br>
  <%= @request.errors.full_messages.join(", ") %>
  <%= form_for @request do |f| %>
    <div class="form-group">
      <%=f.label :name %>
      <%=f.text_field :name %>
    </div>
    <br>
    <div class="form-group">
      <%=f.label :email %>
      <%=f.text_field :email %>
    </div>
    <br>
    <div class="form-group">
      <%=f.label :department %>
      <%= f.radio_button :department, 'Sales' %> Sales
      <%= f.radio_button :department, 'Marketing' %> Marketing
      <%= f.radio_button :department, 'Technical' %> Technical
    </div>
    <br>
    <div class="form-group">
      <%=f.label :message %>
      <%=f.text_area :message %>
    </div>
    <br>

    <%= f.submit "save" %>
  <%end%>
</div>

Quiz-2/app/views/requests/show.html.erb
<div class="container">
  <h2><%= @request.name %></h2>
  <p>Email: <%= @request.email %></p>
  <p>Department: <%= @request.department %></p>
  <p>Message: <%= @request.message %></p>
  <p>Action: <%= @request.actions %></p>
  <br>
  <div>
    <%= link_to "Edit", edit_request_path(@request)%>
    <br>
    <br>
    <%= link_to "Delete", request_path(@request),
                          method: :delete,
                          data: {confirm: 'Are you sure you want to delete this request?'}%>
  </div>

</div>